# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDMK_DIR          = /usr/share/arduino

BOARD_TAG          = uno

MONITOR_BAUDRATE   = 9600

USER_LIB_PATH      = ./libraries

ARDUINO_LIBS       = SoftwareSerial EEPROM LiquidCrystal OneWire DallasTemperature Hx711 TaskScheduler

MONITOR_PORT       = /dev/ttyACM0

### Do not touch - the path to Arduino.mk, inside the ARDMK_DIR
include $(ARDMK_DIR)/Arduino.mk
