#!/bin/bash

eval $(sed '/(\*/,/\*)/d' /etc/brewisd.conf)

pidfile="${pidfile:-/var/run/brewisd.pid}"

if [ -f "$pidfile" ]; then
    pid=$(cat "$pidfile")
fi

check_daemon ()
{
    running=0

    if [ -n "$pid" ]; then
        ps -p "$pid" > /dev/null

        if [ $? -eq 0 ]; then
            # PID file and associated process exist
            running=1
        else
            # PID file exists, but there is not process with that PID
            rm "$pidfile"
        fi
    fi

    return $running
}

start_daemon ()
{
    check_daemon

    if [ $? -eq 0 ]; then
        ./brewisd &
        echo "Daemon started"
    else
        echo "Daemon already running with PID: $pid"
    fi
}

stop_daemon ()
{
    check_daemon

    if [ $? -ne 0 ]; then
        kill -s SIGTERM "$pid"
        echo "SIGTERM sent to PID: $pid"
    else
        echo "Daemon not started"
    fi

    while [ -f "$pidfile" ]; do
        sleep 1
    done

    unset pid
}

case "$1" in
    start)
        start_daemon
    ;;

    stop)
        stop_daemon
    ;;

    restart)
        stop_daemon
        start_daemon
    ;;

    *)
        printf "\033[31;5;148mError\033[39m: usage $0 { start | stop | restart }\r\n"
        exit 1
    ;;
esac

exit 0
