version: '3.4'

services:
  web:
    build:
      context: .
    ports:
      - 8080:80
      - 8081:443
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - brewis-pgdata:/var/lib/postgresql/data

volumes:
  brewis-pgdata:
